-- main pipeline script
-- moves and processes data from raw source through clean and dimensional layers up to data mart


-- run initialization
-- inserts a new run record into etl.etl_runs and captures run context in a temp table named current_run (session scoped)
-- INSERT ... RETURNING captures the exact run_id generated by this session
-- DROP + CREATE - so the temp table is always rebuilt fresh even if the pipeline is re-executed within same session
DROP TABLE IF EXISTS current_run;
CREATE TEMP TABLE current_run (
    run_id BIGINT,
    watermark_lower_bound TIMESTAMP,
    watermark_upper_bound TIMESTAMP)
;

BEGIN;
WITH bounds AS (
    SELECT COALESCE(MAX(watermark_upper_bound), '1900-01-01'::TIMESTAMP) AS lower_bound,
           CURRENT_TIMESTAMP AS upper_bound
    FROM etl.etl_runs
    WHERE status = 'COMPLETED'),
new_run AS (
    INSERT INTO etl.etl_runs (started_at, status, watermark_lower_bound, watermark_upper_bound)
    SELECT CURRENT_TIMESTAMP,
           'RUNNING',
           lower_bound,
           upper_bound
    FROM bounds
    RETURNING run_id, watermark_lower_bound, watermark_upper_bound)
INSERT INTO current_run (run_id, watermark_lower_bound, watermark_upper_bound)
SELECT run_id, watermark_lower_bound, watermark_upper_bound
FROM new_run
;
COMMIT;


-- DQ logging through run completion commits as one unit; failed runs keep the initialized RUNNING audit row
-- dq logging - raw.raw_customers

-- catches records with missing company_name, country, industry, or signup_date
-- detail lists exactly which columns are NULL for faster investigation
BEGIN;
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_customers',
        customer_id,
        'NULL_VALUE',
        CONCAT_WS(', ',
           CASE WHEN company_name IS NULL THEN 'company_name IS NULL' END,
           CASE WHEN country IS NULL THEN 'country IS NULL' END,
           CASE WHEN industry IS NULL THEN 'industry IS NULL' END,
           CASE WHEN signup_date IS NULL THEN 'signup_date IS NULL' END)
FROM raw.raw_customers
WHERE company_name IS NULL
OR country IS NULL
OR industry IS NULL
OR signup_date IS NULL
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where signup_date falls outside the expected range (2020-2030)
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_customers',
        customer_id,
        'DATE_OUT_OF_RANGE',
        'signup_date = ' || signup_date::TEXT
FROM raw.raw_customers
WHERE signup_date IS NOT NULL
AND (signup_date < '2020-01-01'
OR signup_date > '2030-12-31')
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches duplicated records
-- composite/natural key: company_name + country + signup_date
-- UPPER is used on company_name and country because these are columns where case differences are likely typos
WITH duplicated AS (SELECT UPPER(company_name) AS company_name,
                           UPPER(country) AS country,
                           signup_date,
                           MIN(customer_id) AS min_id
                    FROM raw.raw_customers
                    WHERE company_name IS NOT NULL
                    AND country IS NOT NULL
                    AND signup_date IS NOT NULL
                    GROUP BY UPPER(company_name),
                             UPPER(country),
                             signup_date
                    HAVING COUNT(*) > 1)
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_customers',
        c.customer_id,
        'DUPLICATE',
        'duplicate of customer_id = ' || d.min_id
FROM raw.raw_customers AS c
INNER JOIN duplicated AS d
ON UPPER(c.company_name) = d.company_name
AND UPPER(c.country) = d.country
AND c.signup_date = d.signup_date
WHERE c.customer_id > d.min_id
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- dq logging - raw.raw_plans

-- catches records with missing plan_name, plan_type, billing_cycle_months, category, or base_price
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_plans',
        plan_id,
        'NULL_VALUE',
        CONCAT_WS(', ',
           CASE WHEN plan_name IS NULL THEN 'plan_name IS NULL' END,
           CASE WHEN plan_type IS NULL THEN 'plan_type IS NULL' END,
           CASE WHEN billing_cycle_months IS NULL THEN 'billing_cycle_months IS NULL' END,
           CASE WHEN category IS NULL THEN 'category IS NULL' END,
           CASE WHEN base_price IS NULL THEN 'base_price IS NULL' END)
FROM raw.raw_plans
WHERE plan_name IS NULL
OR plan_type IS NULL
OR billing_cycle_months IS NULL
OR category IS NULL
OR base_price IS NULL
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where plan_type is not NULL but does not match the list of allowed categories
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_plans',
        plan_id,
        'INVALID_CATEGORY',
        'plan_type = ' || plan_type
FROM raw.raw_plans
WHERE plan_type IS NOT NULL
AND plan_type NOT IN ('Monthly', 'Annual')
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where category is not NULL but does not match the list of allowed categories
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_plans',
        plan_id,
        'INVALID_CATEGORY',
        'category = ' || category
FROM raw.raw_plans
WHERE category IS NOT NULL
AND category NOT IN ('Starter', 'Professional', 'Enterprise')
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where base_price is negative or billing_cycle_months is zero or negative
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_plans',
        plan_id,
        'NEGATIVE_NUMBER',
        CONCAT_WS(', ',
           CASE WHEN base_price IS NOT NULL
                AND base_price < 0
                THEN 'base_price = ' || base_price::TEXT END,
           CASE WHEN billing_cycle_months IS NOT NULL
                AND billing_cycle_months <= 0
                THEN 'billing_cycle_months = ' || billing_cycle_months::TEXT END)
FROM raw.raw_plans
WHERE (base_price IS NOT NULL AND base_price < 0)
OR (billing_cycle_months IS NOT NULL AND billing_cycle_months <= 0)
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches duplicated records
-- composite/natural key: plan_name + plan_type
WITH duplicated AS (SELECT UPPER(plan_name) AS plan_name,
                           plan_type,
                           MIN(plan_id) AS min_id
                    FROM raw.raw_plans
                    WHERE plan_name IS NOT NULL
                    AND plan_type IS NOT NULL
                    GROUP BY UPPER(plan_name),
                             plan_type
                    HAVING COUNT(*) > 1)
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_plans',
        p.plan_id,
        'DUPLICATE',
        'duplicate of plan_id = ' || d.min_id
FROM raw.raw_plans AS p
INNER JOIN duplicated AS d
ON UPPER(p.plan_name) = d.plan_name
AND p.plan_type = d.plan_type
WHERE p.plan_id > d.min_id
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- dq logging - raw.raw_subscriptions

-- catches records with missing customer_id, plan_id, or start_date
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_subscriptions',
        sub_id,
        'NULL_VALUE',
        CONCAT_WS(', ',
           CASE WHEN customer_id IS NULL THEN 'customer_id IS NULL' END,
           CASE WHEN plan_id IS NULL THEN 'plan_id IS NULL' END,
           CASE WHEN start_date IS NULL THEN 'start_date IS NULL' END)
FROM raw.raw_subscriptions
WHERE customer_id IS NULL
OR plan_id IS NULL
OR start_date IS NULL
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where end_date comes before start_date
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_subscriptions',
        sub_id,
        'DATE_LOGIC_ERROR_DATES',
        'end_date (' || end_date::TEXT || ') < start_date (' || start_date::TEXT || ')'
FROM raw.raw_subscriptions
WHERE end_date IS NOT NULL
AND start_date IS NOT NULL
AND end_date < start_date
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where the linked customer's signup_date appears after the subscription start_date
-- please see the documentation for explanation about distinction between DATE_LOGIC_ERROR_DATES and DATE_LOGIC_ERROR_SIGNUP
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_subscriptions',
        s.sub_id,
        'DATE_LOGIC_ERROR_SIGNUP',
        'signup_date (' || c.signup_date::TEXT || ') > start_date (' || s.start_date::TEXT || ')'
FROM raw.raw_subscriptions AS s
INNER JOIN raw.raw_customers AS c
ON c.customer_id = s.customer_id
WHERE c.signup_date IS NOT NULL
AND s.start_date IS NOT NULL
AND c.signup_date > s.start_date
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where start_date or end_date falls outside the expected range (2020-2030)
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_subscriptions',
        sub_id,
        'DATE_OUT_OF_RANGE',
        CONCAT_WS(', ',
           CASE WHEN start_date IS NOT NULL
                 AND (start_date < '2020-01-01' OR start_date > '2030-12-31')
                 THEN 'start_date = ' || start_date::TEXT END,
           CASE WHEN end_date IS NOT NULL
                 AND (end_date < '2020-01-01' OR end_date > '2030-12-31')
                 THEN 'end_date = ' || end_date::TEXT END)
FROM raw.raw_subscriptions
WHERE (start_date IS NOT NULL AND (start_date < '2020-01-01' OR start_date > '2030-12-31'))
OR (end_date IS NOT NULL AND (end_date < '2020-01-01' OR end_date > '2030-12-31'))
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where amount is a negative or zero number
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_subscriptions',
        sub_id,
        'NEGATIVE_NUMBER',
        CASE WHEN amount = 0
             THEN 'amount = 0 (zero-amount subscriptions are not allowed)'
             ELSE 'amount = ' || amount::TEXT
        END
FROM raw.raw_subscriptions
WHERE amount IS NOT NULL
AND amount <= 0
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches duplicated records
-- composite/natural key: customer_id + plan_id + start_date
WITH duplicated AS (SELECT customer_id,
                           plan_id,
                           start_date,
                           MIN(sub_id) AS min_id
                    FROM raw.raw_subscriptions
                    WHERE customer_id IS NOT NULL
                    AND plan_id IS NOT NULL
                    AND start_date IS NOT NULL
                    GROUP BY customer_id,
                             plan_id,
                             start_date
                    HAVING COUNT(*) > 1)
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_subscriptions',
        s.sub_id,
        'DUPLICATE',
        'duplicate of sub_id = ' || d.min_id
FROM raw.raw_subscriptions AS s
INNER JOIN duplicated AS d
ON d.customer_id = s.customer_id
AND d.plan_id = s.plan_id
AND d.start_date = s.start_date
WHERE s.sub_id > d.min_id
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches subscriptions where customer_id has no matching record in raw.raw_customers
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail, detail_key)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_subscriptions',
        s.sub_id,
        'MISSING_FK',
        'customer_id = ' || s.customer_id || ' not found in raw.raw_customers',
        'customer_id'
FROM raw.raw_subscriptions AS s
WHERE s.customer_id IS NOT NULL
AND NOT EXISTS (SELECT 1
                FROM raw.raw_customers AS c
                WHERE c.customer_id = s.customer_id)
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches subscriptions where plan_id has no matching record in raw.raw_plans
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail, detail_key)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_subscriptions',
        s.sub_id,
        'MISSING_FK',
        'plan_id = ' || s.plan_id || ' not found in raw.raw_plans',
        'plan_id'
FROM raw.raw_subscriptions AS s
WHERE s.plan_id IS NOT NULL
AND NOT EXISTS (SELECT 1
                FROM raw.raw_plans AS p
                WHERE p.plan_id = s.plan_id)
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- dq logging - raw.raw_transactions

-- catches records with missing sub_id, tx_date, or status
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_transactions',
        tx_id,
        'NULL_VALUE',
        CONCAT_WS(', ',
           CASE WHEN sub_id IS NULL THEN 'sub_id IS NULL' END,
           CASE WHEN tx_date IS NULL THEN 'tx_date IS NULL' END,
           CASE WHEN status IS NULL THEN 'status IS NULL' END)
FROM raw.raw_transactions
WHERE sub_id IS NULL
OR tx_date IS NULL
OR status IS NULL
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where status is not NULL but does not match the list of allowed categories
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_transactions',
        tx_id,
        'INVALID_CATEGORY',
        'status = ' || status
FROM raw.raw_transactions
WHERE status IS NOT NULL
AND status NOT IN ('Success', 'Failed', 'Refunded')
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where tx_date starts before the linked subscription start_date
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_transactions',
        t.tx_id,
        'DATE_LOGIC_ERROR_DATES',
        'tx_date (' || t.tx_date::TEXT || ') < start_date (' || s.start_date::TEXT || ')'
FROM raw.raw_transactions AS t
INNER JOIN raw.raw_subscriptions AS s
ON s.sub_id = t.sub_id
WHERE t.tx_date IS NOT NULL
AND s.start_date IS NOT NULL
AND t.tx_date < s.start_date
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where tx_date falls outside the expected range (2020-2030)
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_transactions',
        tx_id,
        'DATE_OUT_OF_RANGE',
        'tx_date = ' || tx_date::TEXT
FROM raw.raw_transactions
WHERE tx_date IS NOT NULL
AND (tx_date < '2020-01-01' OR tx_date > '2030-12-31')
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches duplicated records
-- composite/natural key: sub_id + tx_date + status
WITH duplicated AS (SELECT sub_id,
                           tx_date,
                           status,
                           MIN(tx_id) AS min_id
                    FROM raw.raw_transactions
                    WHERE sub_id IS NOT NULL
                    AND tx_date IS NOT NULL
                    AND status IS NOT NULL
                    GROUP BY sub_id,
                             tx_date,
                             status
                    HAVING COUNT(*) > 1)
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_transactions',
        t.tx_id,
        'DUPLICATE',
        'duplicate of tx_id = ' || d.min_id
FROM raw.raw_transactions AS t
INNER JOIN duplicated AS d
ON d.sub_id = t.sub_id
AND d.tx_date = t.tx_date
AND d.status = t.status
WHERE t.tx_id > d.min_id
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where sub_id has no matching record in raw.raw_subscriptions
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_transactions',
        t.tx_id,
        'MISSING_FK',
        'sub_id = ' || t.sub_id || ' not found in raw.raw_subscriptions'
FROM raw.raw_transactions AS t
WHERE t.sub_id IS NOT NULL
AND NOT EXISTS (SELECT 1
                FROM raw.raw_subscriptions AS s
                WHERE s.sub_id = t.sub_id)
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records with missing transaction amount
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_transactions',
        tx_id,
        'NULL_VALUE',
        'amount IS NULL'
FROM raw.raw_transactions
WHERE amount IS NULL
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where transaction amount is negative; 0.00 is valid for Failed transactions
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_transactions',
        tx_id,
        'NEGATIVE_NUMBER',
        'amount = ' || amount::TEXT
FROM raw.raw_transactions
WHERE amount IS NOT NULL
AND amount < 0
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches records where tx_date falls after the linked subscription end_date
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'raw.raw_transactions',
        t.tx_id,
        'DATE_LOGIC_ERROR_DATES',
        'tx_date (' || t.tx_date::TEXT || ') > end_date (' || s.end_date::TEXT || ')'
FROM raw.raw_transactions AS t
INNER JOIN raw.raw_subscriptions AS s
ON s.sub_id = t.sub_id
WHERE t.tx_date IS NOT NULL
AND s.end_date IS NOT NULL
AND t.tx_date > s.end_date
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- CLEAN UPSERTS

-- upsert into clean.clean_customers
-- surrogate PK is auto-generated; raw customer_id stored as source_customer_id
-- UPPER applied to company_name and country for deduplication normalization and case-insensitive change detection
-- incremental filter: processes rows with ingested_at inside the current run watermark window
WITH deduped AS (SELECT customer_id AS source_customer_id,
                        company_name,
                        country,
                        industry,
                        signup_date,
                        source_updated_at,
                        ROW_NUMBER() OVER (PARTITION BY UPPER(company_name),
                                                        UPPER(country),
                                                        signup_date
                                           ORDER BY customer_id ASC) AS rn
                 FROM raw.raw_customers AS r
                 WHERE company_name IS NOT NULL
                 AND country IS NOT NULL
                 AND industry IS NOT NULL
                 AND signup_date IS NOT NULL
                 AND signup_date BETWEEN '2020-01-01' AND '2030-12-31'
                 AND r.ingested_at > (SELECT watermark_lower_bound FROM current_run)
                 AND r.ingested_at <= (SELECT watermark_upper_bound FROM current_run))
INSERT INTO clean.clean_customers (source_customer_id,
                                   company_name,
                                   country,
                                   industry,
                                   signup_date,
                                   source_updated_at,
                                   created_at,
                                   updated_at)
SELECT source_customer_id,
       company_name,
       country,
       industry,
       signup_date,
       source_updated_at,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM deduped
WHERE rn = 1
ON CONFLICT (source_customer_id) DO UPDATE
    SET company_name = EXCLUDED.company_name,
        country = EXCLUDED.country,
        industry = EXCLUDED.industry,
        signup_date = EXCLUDED.signup_date,
        source_updated_at = EXCLUDED.source_updated_at,
        updated_at = CURRENT_TIMESTAMP
WHERE UPPER(clean.clean_customers.company_name) IS DISTINCT FROM UPPER(EXCLUDED.company_name)
OR UPPER(clean.clean_customers.country) IS DISTINCT FROM UPPER(EXCLUDED.country)
OR clean.clean_customers.industry IS DISTINCT FROM EXCLUDED.industry
OR clean.clean_customers.signup_date IS DISTINCT FROM EXCLUDED.signup_date
OR clean.clean_customers.source_updated_at IS DISTINCT FROM EXCLUDED.source_updated_at
;


-- upsert into clean.clean_plans
-- surrogate PK is auto-generated; raw plan_id stored as source_plan_id 
-- invalid plan_type, category, base_price, and billing_cycle_months are filtered out at this layer
-- UPPER(plan_name) is used only for deduplication
-- full reconciliation: dim_plan is SCD1
WITH deduped AS (SELECT plan_id AS source_plan_id,
                        plan_name,
                        plan_type,
                        billing_cycle_months,
                        category,
                        base_price,
                        source_updated_at,
                        ROW_NUMBER() OVER (PARTITION BY UPPER(plan_name),
                                                        plan_type
                                           ORDER BY plan_id ASC) AS rn
                 FROM raw.raw_plans AS r
                 WHERE plan_name IS NOT NULL
                 AND plan_type IS NOT NULL
                 AND billing_cycle_months IS NOT NULL
                 AND category IS NOT NULL
                 AND base_price IS NOT NULL
                 AND plan_type IN ('Monthly', 'Annual')
                 AND category IN ('Starter', 'Professional', 'Enterprise')
                 AND base_price > 0
                 AND billing_cycle_months > 0)
INSERT INTO clean.clean_plans (source_plan_id,
                               plan_name,
                               plan_type,
                               billing_cycle_months,
                               category,
                               base_price,
                               source_updated_at,
                               created_at,
                               updated_at)
SELECT source_plan_id,
       plan_name,
       plan_type,
       billing_cycle_months,
       category,
       base_price,
       source_updated_at,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM deduped
WHERE rn = 1
ON CONFLICT (source_plan_id) DO UPDATE
    SET plan_name = EXCLUDED.plan_name,
        plan_type = EXCLUDED.plan_type,
        billing_cycle_months = EXCLUDED.billing_cycle_months,
        category = EXCLUDED.category,
        base_price = EXCLUDED.base_price,
        source_updated_at = EXCLUDED.source_updated_at,
        updated_at = CURRENT_TIMESTAMP
WHERE clean.clean_plans.plan_name IS DISTINCT FROM EXCLUDED.plan_name
OR clean.clean_plans.plan_type IS DISTINCT FROM EXCLUDED.plan_type
OR clean.clean_plans.billing_cycle_months IS DISTINCT FROM EXCLUDED.billing_cycle_months
OR clean.clean_plans.category IS DISTINCT FROM EXCLUDED.category
OR clean.clean_plans.base_price IS DISTINCT FROM EXCLUDED.base_price
OR clean.clean_plans.source_updated_at IS DISTINCT FROM EXCLUDED.source_updated_at
;


-- upsert into clean.clean_subscriptions
-- surrogate PK is auto-generated; raw sub_id stored as source_sub_id 
-- zero-amount subscriptions are treated as DQ issues and filtered out at this layer
-- incremental filter: processes rows with ingested_at inside the current run watermark window
WITH deduped AS (SELECT s.sub_id AS source_sub_id,
                        cc.customer_id,
                        cp.plan_id,
                        s.start_date,
                        s.end_date,
                        s.amount,
                        s.source_updated_at,
                        ROW_NUMBER() OVER (PARTITION BY s.customer_id,
                                                        s.plan_id,
                                                        s.start_date
                                           ORDER BY s.sub_id ASC) AS rn
                 FROM raw.raw_subscriptions AS s
                 INNER JOIN clean.clean_customers AS cc
                 ON cc.source_customer_id = s.customer_id
                 INNER JOIN clean.clean_plans AS cp
                 ON cp.source_plan_id = s.plan_id
                 WHERE s.customer_id IS NOT NULL
                 AND s.plan_id IS NOT NULL
                 AND s.start_date IS NOT NULL
                 AND (s.end_date IS NULL OR s.end_date >= s.start_date)
                 AND s.start_date BETWEEN '2020-01-01' AND '2030-12-31'
                 AND (s.end_date IS NULL OR s.end_date BETWEEN '2020-01-01' AND '2030-12-31')
                 AND s.amount IS NOT NULL
                 AND s.amount > 0
                 AND cc.signup_date <= s.start_date
                 AND s.ingested_at > (SELECT watermark_lower_bound FROM current_run)
                 AND s.ingested_at <= (SELECT watermark_upper_bound FROM current_run))
INSERT INTO clean.clean_subscriptions (source_sub_id,
                                       customer_id,
                                       plan_id,
                                       start_date,
                                       end_date,
                                       amount,
                                       source_updated_at,
                                       created_at,
                                       updated_at)
SELECT source_sub_id,
       customer_id,
       plan_id,
       start_date,
       end_date,
       amount,
       source_updated_at,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM deduped
WHERE rn = 1
ON CONFLICT (source_sub_id) DO UPDATE
    SET customer_id = EXCLUDED.customer_id,
        plan_id = EXCLUDED.plan_id,
        start_date = EXCLUDED.start_date,
        end_date = EXCLUDED.end_date,
        amount = EXCLUDED.amount,
        source_updated_at = EXCLUDED.source_updated_at,
        updated_at = CURRENT_TIMESTAMP
WHERE clean.clean_subscriptions.customer_id IS DISTINCT FROM EXCLUDED.customer_id
OR clean.clean_subscriptions.plan_id IS DISTINCT FROM EXCLUDED.plan_id
OR clean.clean_subscriptions.start_date IS DISTINCT FROM EXCLUDED.start_date
OR clean.clean_subscriptions.end_date IS DISTINCT FROM EXCLUDED.end_date
OR clean.clean_subscriptions.amount IS DISTINCT FROM EXCLUDED.amount
OR clean.clean_subscriptions.source_updated_at IS DISTINCT FROM EXCLUDED.source_updated_at
;


-- upsert into clean.clean_transactions
-- surrogate PK is auto-generated; raw tx_id stored as source_tx_id
-- amount propagated from raw; non-null amount >= 0 enforced (0.00 is valid for failed transactions)
-- tx_date <= end_date enforced after DQ logging catches post-end-date transactions
-- incremental filter: processes rows with ingested_at inside the current run watermark window
WITH deduped AS (SELECT t.tx_id AS source_tx_id,
                        cs.sub_id,
                        t.tx_date,
                        t.status,
                        t.amount,
                        ROW_NUMBER() OVER (PARTITION BY t.sub_id,
                                                        t.tx_date,
                                                        t.status
                                           ORDER BY t.tx_id ASC) AS rn
                 FROM raw.raw_transactions AS t
                 INNER JOIN clean.clean_subscriptions AS cs
                 ON cs.source_sub_id = t.sub_id
                 WHERE t.sub_id IS NOT NULL
                 AND t.tx_date IS NOT NULL
                 AND t.status IS NOT NULL
                 AND t.status IN ('Success', 'Failed', 'Refunded')
                 AND t.amount IS NOT NULL
                 AND t.amount >= 0
                 AND t.tx_date >= cs.start_date
                 AND (cs.end_date IS NULL OR t.tx_date <= cs.end_date)
                 AND t.tx_date BETWEEN '2020-01-01' AND '2030-12-31'
                 AND t.ingested_at > (SELECT watermark_lower_bound FROM current_run)
                 AND t.ingested_at <= (SELECT watermark_upper_bound FROM current_run))
INSERT INTO clean.clean_transactions (source_tx_id,
                                      sub_id,
                                      tx_date,
                                      status,
                                      amount,
                                      created_at,
                                      updated_at)
SELECT source_tx_id,
       sub_id,
       tx_date,
       status,
       amount,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM deduped
WHERE rn = 1
ON CONFLICT (source_tx_id) DO UPDATE
    SET sub_id = EXCLUDED.sub_id,
        tx_date = EXCLUDED.tx_date,
        status = EXCLUDED.status,
        amount = EXCLUDED.amount,
        updated_at = CURRENT_TIMESTAMP
WHERE clean.clean_transactions.sub_id IS DISTINCT FROM EXCLUDED.sub_id
OR clean.clean_transactions.tx_date IS DISTINCT FROM EXCLUDED.tx_date
OR clean.clean_transactions.status IS DISTINCT FROM EXCLUDED.status
OR clean.clean_transactions.amount IS DISTINCT FROM EXCLUDED.amount
;


-- DIMENSIONAL LAYER

-- load dimensional.dim_date
-- generates one row per calendar day for 2020-2030
-- date_key is an integer in YYYYMMDD format for efficient joining with fact tables
-- week_of_year uses week numbering EXTRACT(WEEK FROM ...)
INSERT INTO dimensional.dim_date (date_key,
                                  full_date,
                                  year,
                                  quarter,
                                  month,
                                  month_name,
                                  day_of_month,
                                  day_of_week,
                                  day_name,
                                  is_weekend,
                                  week_of_year)
SELECT TO_CHAR(d, 'YYYYMMDD')::INT AS date_key,
       d::DATE AS full_date,
       EXTRACT(YEAR FROM d)::INT AS year,
       EXTRACT(QUARTER FROM d)::INT AS quarter,
       EXTRACT(MONTH FROM d)::INT AS month,
       TO_CHAR(d, 'FMMonth') AS month_name,
       EXTRACT(DAY FROM d)::INT AS day_of_month,
       EXTRACT(ISODOW FROM d)::INT AS day_of_week,
       TO_CHAR(d, 'FMDay') AS day_name,
       EXTRACT(ISODOW FROM d)::INT IN (6, 7) AS is_weekend,
       EXTRACT(WEEK FROM d)::INT AS week_of_year
FROM generate_series('2020-01-01'::DATE, '2030-12-31'::DATE, INTERVAL '1 day') AS d
ON CONFLICT (date_key) DO NOTHING
;


-- load dimensional.dim_plan - SCD type 1
-- reads from clean.clean_plans; source_plan_id used 
-- SCD1: changes to plan attributes overwrite old values, no history is kept
INSERT INTO dimensional.dim_plan (source_plan_id,
                                  plan_name,
                                  plan_type,
                                  billing_cycle_months,
                                  category,
                                  base_price,
                                  created_at,
                                  updated_at)
SELECT source_plan_id,
       plan_name,
       plan_type,
       billing_cycle_months,
       category,
       base_price,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM clean.clean_plans
ON CONFLICT (source_plan_id) DO UPDATE
    SET plan_name = EXCLUDED.plan_name,
        plan_type = EXCLUDED.plan_type,
        billing_cycle_months = EXCLUDED.billing_cycle_months,
        category = EXCLUDED.category,
        base_price = EXCLUDED.base_price,
        updated_at = CURRENT_TIMESTAMP
WHERE dimensional.dim_plan.plan_name IS DISTINCT FROM EXCLUDED.plan_name
OR dimensional.dim_plan.plan_type IS DISTINCT FROM EXCLUDED.plan_type
OR dimensional.dim_plan.billing_cycle_months IS DISTINCT FROM EXCLUDED.billing_cycle_months
OR dimensional.dim_plan.category IS DISTINCT FROM EXCLUDED.category
OR dimensional.dim_plan.base_price IS DISTINCT FROM EXCLUDED.base_price
;


-- load dimensional.dim_customer - SCD type 2
-- tracked attributes: company_name, country, industry
-- step A closes versions where tracked attributes have changed since last run
-- step B inserts new versions for changed customers and new customers
-- company_name and country comparisons are case-insensitive so cosmetic casing changes do not create phantom history
-- step A closes using c.source_updated_at::DATE - 1 day so version boundaries come from the source change timestamp, not ETL execution time
-- step B opens changed versions at c.source_updated_at::DATE; first versions open at signup_date
-- raw UPDATE statements must refresh ingested_at so clean receives changed rows before this SCD2 step runs
-- idempotent: step A finds no mismatches if attributes unchanged; step B inserts nothing if all have is_current = TRUE

-- step A: close expired versions where tracked attributes differ from current clean values
UPDATE dimensional.dim_customer AS d
SET valid_to = c.source_updated_at::DATE - INTERVAL '1 day',
    is_current = FALSE,
    updated_at = CURRENT_TIMESTAMP
FROM clean.clean_customers AS c
WHERE d.source_customer_id = c.source_customer_id
AND d.is_current = TRUE
AND (UPPER(d.company_name) IS DISTINCT FROM UPPER(c.company_name)
     OR UPPER(d.country) IS DISTINCT FROM UPPER(c.country)
     OR d.industry IS DISTINCT FROM c.industry)
;

-- step B: insert new versions for changed customers (no is_current = TRUE row after step A), and new customers 
INSERT INTO dimensional.dim_customer (source_customer_id,
                                      company_name,
                                      country,
                                      industry,
                                      signup_date,
                                      source_updated_at,
                                      valid_from,
                                      valid_to,
                                      is_current,
                                      created_at,
                                      updated_at)
SELECT c.source_customer_id,
       c.company_name,
       c.country,
       c.industry,
       c.signup_date,
       c.source_updated_at,
       CASE WHEN EXISTS (SELECT 1
                         FROM dimensional.dim_customer AS d2
                         WHERE d2.source_customer_id = c.source_customer_id)
            THEN c.source_updated_at::DATE
            ELSE c.signup_date::DATE
       END AS valid_from,
       '9999-12-31' AS valid_to,
       TRUE AS is_current,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM clean.clean_customers AS c
WHERE NOT EXISTS (SELECT 1
                  FROM dimensional.dim_customer AS d
                  WHERE d.source_customer_id = c.source_customer_id
                  AND d.is_current = TRUE)
;


-- load dimensional.fact_subscription
-- one row per subscription
-- customer_id FK pinned to the dim_customer version current at subscription start_date (SCD2 resolution)
-- end_date_key is NULL for active subscriptions; subscription_duration_days is NULL for active subscriptions
-- is_active and subscription_duration_days are refreshed denormalizations derived from end_date
-- tx_agg CTE aggregates clean.clean_transactions by sub_id for the four transaction measure columns
-- LEFT JOIN ensures subscriptions with zero transactions load with measures defaulting to 0
-- ON CONFLICT refreshes all measures so newly loaded clean transactions are reflected
-- sum_successful_payments is the actual sum of collected payment amounts (ct.amount) for successful transactions; each transaction carries its own amount propagated from raw.raw_transactions
WITH tx_agg AS (SELECT ct.sub_id,
                       COUNT(*) FILTER (WHERE ct.status = 'Success') AS total_successful_payments,
                       COUNT(*) FILTER (WHERE ct.status = 'Failed') AS total_failed_payments,
                       COUNT(*) FILTER (WHERE ct.status = 'Refunded') AS total_refunded_payments,
                       SUM(ct.amount) FILTER (WHERE ct.status = 'Success') AS sum_successful_payments
                FROM clean.clean_transactions AS ct
                GROUP BY ct.sub_id)
INSERT INTO dimensional.fact_subscription (sub_id,
                                           customer_id,
                                           plan_id,
                                           start_date_key,
                                           end_date_key,
                                           amount,
                                           subscription_duration_days,
                                           is_active,
                                           total_successful_payments,
                                           total_failed_payments,
                                           total_refunded_payments,
                                           sum_successful_payments)
SELECT cs.source_sub_id AS sub_id,
       dc.customer_id,
       dp.plan_id,
       TO_CHAR(cs.start_date, 'YYYYMMDD')::INT AS start_date_key,
       CASE WHEN cs.end_date IS NOT NULL
            THEN TO_CHAR(cs.end_date, 'YYYYMMDD')::INT
       END AS end_date_key,
       cs.amount,
       (cs.end_date - cs.start_date) AS subscription_duration_days,
       (cs.end_date IS NULL) AS is_active,
       COALESCE(ta.total_successful_payments, 0) AS total_successful_payments,
       COALESCE(ta.total_failed_payments, 0) AS total_failed_payments,
       COALESCE(ta.total_refunded_payments, 0) AS total_refunded_payments,
       COALESCE(ta.sum_successful_payments, 0) AS sum_successful_payments
FROM clean.clean_subscriptions AS cs
INNER JOIN clean.clean_customers AS cc
ON cc.customer_id = cs.customer_id
INNER JOIN dimensional.dim_customer AS dc
ON dc.source_customer_id = cc.source_customer_id
AND cs.start_date >= dc.valid_from
AND cs.start_date <= dc.valid_to
INNER JOIN clean.clean_plans AS cp
ON cp.plan_id = cs.plan_id
INNER JOIN dimensional.dim_plan AS dp
ON dp.source_plan_id = cp.source_plan_id
LEFT JOIN tx_agg AS ta
ON ta.sub_id = cs.sub_id
ON CONFLICT (sub_id) DO UPDATE
    SET customer_id = EXCLUDED.customer_id,
        plan_id = EXCLUDED.plan_id,
        start_date_key = EXCLUDED.start_date_key,
        end_date_key = EXCLUDED.end_date_key,
        amount = EXCLUDED.amount,
        subscription_duration_days = EXCLUDED.subscription_duration_days,
        is_active = EXCLUDED.is_active,
        total_successful_payments = EXCLUDED.total_successful_payments,
        total_failed_payments = EXCLUDED.total_failed_payments,
        total_refunded_payments = EXCLUDED.total_refunded_payments,
        sum_successful_payments = EXCLUDED.sum_successful_payments
;


-- load dimensional.fact_transaction
-- grain: one row per accepted transaction
-- customer_id and plan_id inherited from fact_subscription: reuses the SCD2 pin already computed
-- clean transaction sub_id is a clean surrogate, so clean_subscriptions bridges it back to fact_subscription.sub_id
-- is_success/is_failed/is_refunded replace the status string for analytical convenience
-- ON CONFLICT refreshes changed columns so rerunning is safe
INSERT INTO dimensional.fact_transaction (tx_id,
                                          sub_id,
                                          customer_id,
                                          plan_id,
                                          date_key,
                                          amount,
                                          is_success,
                                          is_failed,
                                          is_refunded,
                                          created_at,
                                          updated_at)
SELECT ct.source_tx_id AS tx_id,
       fs.sub_id AS sub_id,
       fs.customer_id,
       fs.plan_id,
       TO_CHAR(ct.tx_date, 'YYYYMMDD')::INT AS date_key,
       ct.amount,
       (ct.status = 'Success') AS is_success,
       (ct.status = 'Failed') AS is_failed,
       (ct.status = 'Refunded') AS is_refunded,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM clean.clean_transactions AS ct
INNER JOIN clean.clean_subscriptions AS cs
ON cs.sub_id = ct.sub_id
INNER JOIN dimensional.fact_subscription AS fs
ON fs.sub_id = cs.source_sub_id
ON CONFLICT (tx_id) DO UPDATE
    SET sub_id = EXCLUDED.sub_id,
        customer_id = EXCLUDED.customer_id,
        plan_id = EXCLUDED.plan_id,
        date_key = EXCLUDED.date_key,
        amount = EXCLUDED.amount,
        is_success = EXCLUDED.is_success,
        is_failed = EXCLUDED.is_failed,
        is_refunded = EXCLUDED.is_refunded,
        updated_at = CURRENT_TIMESTAMP
WHERE dimensional.fact_transaction.customer_id IS DISTINCT FROM EXCLUDED.customer_id
OR dimensional.fact_transaction.sub_id IS DISTINCT FROM EXCLUDED.sub_id
OR dimensional.fact_transaction.plan_id IS DISTINCT FROM EXCLUDED.plan_id
OR dimensional.fact_transaction.date_key IS DISTINCT FROM EXCLUDED.date_key
OR dimensional.fact_transaction.amount IS DISTINCT FROM EXCLUDED.amount
OR dimensional.fact_transaction.is_success IS DISTINCT FROM EXCLUDED.is_success
OR dimensional.fact_transaction.is_failed IS DISTINCT FROM EXCLUDED.is_failed
OR dimensional.fact_transaction.is_refunded IS DISTINCT FROM EXCLUDED.is_refunded
;


-- dq verification - dimensional facts

-- catches clean subscriptions that still have no fact row after dimensional load
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'dimensional.fact_subscription',
        cs.source_sub_id,
        'MISSING_FK',
        'source_customer_id = ' || cc.source_customer_id || ', start_date = ' || cs.start_date::TEXT
            || ' has no matching fact_subscription row'
FROM clean.clean_subscriptions AS cs
INNER JOIN clean.clean_customers AS cc
ON cc.customer_id = cs.customer_id
WHERE NOT EXISTS (SELECT 1
                  FROM dimensional.fact_subscription AS fs
                  WHERE fs.sub_id = cs.source_sub_id)
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches fact rows where is_active and end_date_key disagree
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'dimensional.fact_subscription',
        fs.sub_id,
        'DERIVED_VALUE_MISMATCH',
        'is_active = ' || fs.is_active::TEXT || ', end_date_key = ' || COALESCE(fs.end_date_key::TEXT, 'NULL')
FROM dimensional.fact_subscription AS fs
WHERE fs.is_active IS DISTINCT FROM (fs.end_date_key IS NULL)
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- catches clean transactions that still have no fact_transaction row after dimensional load
INSERT INTO etl.dq_log (run_id, last_seen_run_id, table_name, record_id, issue_type, detail)
SELECT (SELECT run_id FROM current_run),
       (SELECT run_id FROM current_run),
        'dimensional.fact_transaction',
        ct.source_tx_id,
        'MISSING_FK',
        'source_tx_id = ' || ct.source_tx_id || ' has no matching fact_transaction row'
FROM clean.clean_transactions AS ct
WHERE NOT EXISTS (SELECT 1
                  FROM dimensional.fact_transaction AS ft
                  WHERE ft.tx_id = ct.source_tx_id)
ON CONFLICT (table_name, record_id, issue_type, detail_key) DO UPDATE
    SET last_seen_run_id = EXCLUDED.last_seen_run_id,
        detail = EXCLUDED.detail
;


-- DATA MART

-- refresh mart.dm_sales_performance
REFRESH MATERIALIZED VIEW mart.dm_sales_performance;


-- pipeline completion
-- marks the current run as completed
-- if the pipeline fails before reaching this point, ended_at is NULL and status remains RUNNING
-- a run without COMPLETED status signals that a failure occurred during execution
UPDATE etl.etl_runs
SET ended_at = CURRENT_TIMESTAMP,
    status = 'COMPLETED'
WHERE run_id = (SELECT run_id
                FROM current_run)
;
COMMIT;


-- ad-hoc additional queries for quick summary across all pipeline layers/stages
-- run to check the summary along with DQ issues found during pipeline run

/*

-- overview of DQ log table
SELECT *
FROM etl.dq_log;

SELECT (SELECT run_id
        FROM current_run) AS run_id,
       (SELECT started_at
        FROM etl.etl_runs
        WHERE run_id = (SELECT run_id
                        FROM current_run)) AS run_started_at,
       (SELECT ended_at
        FROM etl.etl_runs
        WHERE run_id = (SELECT run_id
                        FROM current_run)) AS run_ended_at,
       (SELECT status
        FROM etl.etl_runs
        WHERE run_id = (SELECT run_id
                        FROM current_run)) AS run_status,
       -- raw layer
       (SELECT COUNT(*) FROM raw.raw_customers) AS raw_customers,
       (SELECT COUNT(*) FROM raw.raw_plans) AS raw_plans,
       (SELECT COUNT(*) FROM raw.raw_subscriptions) AS raw_subscriptions,
       (SELECT COUNT(*) FROM raw.raw_transactions) AS raw_transactions,
       -- clean layer
       (SELECT COUNT(*) FROM clean.clean_customers) AS clean_customers,
       (SELECT COUNT(*) FROM clean.clean_plans) AS clean_plans,
       (SELECT COUNT(*) FROM clean.clean_subscriptions) AS clean_subscriptions,
       (SELECT COUNT(*) FROM clean.clean_transactions) AS clean_transactions,
       -- dimensional layer
       (SELECT COUNT(*) FROM dimensional.dim_date) AS dim_date,
       (SELECT COUNT(*) FROM dimensional.dim_customer) AS dim_customer_total,
       (SELECT COUNT(*) FROM dimensional.dim_customer WHERE is_current = FALSE) AS dim_customer_historical_versions,
       (SELECT COUNT(*) FROM dimensional.dim_plan) AS dim_plan,
       (SELECT COUNT(*) FROM dimensional.fact_subscription) AS fact_subscription,
       (SELECT COUNT(*) FROM dimensional.fact_transaction) AS fact_transaction,
       -- mart layer
       (SELECT COUNT(*) FROM mart.dm_sales_performance) AS datamart_records,
       -- dq summary
       (SELECT COUNT(*)
        FROM etl.dq_log
        WHERE run_id = (SELECT run_id
                        FROM current_run)) AS dq_issues_new_this_run,
       (SELECT COUNT(*)
        FROM etl.dq_log
        WHERE last_seen_run_id = (SELECT run_id
                                  FROM current_run)
        AND run_id < (SELECT run_id
                      FROM current_run)) AS dq_issues_persisted_this_run,
       (SELECT COUNT(*) FROM etl.dq_log) AS dq_issues_all_time
;

-- DQ issues detail for pipeline execution, by table and type
-- new - first detected this run
-- persisted - detected earlier but still present
SELECT table_name,
       issue_type,
       COUNT(*) FILTER (WHERE run_id = (SELECT run_id
                                        FROM current_run)) AS new_count,
       COUNT(*) FILTER (WHERE run_id < (SELECT run_id
                                        FROM current_run)) AS persisted_count,
       COUNT(*) AS total_count
FROM etl.dq_log
WHERE last_seen_run_id = (SELECT run_id
                          FROM current_run)
GROUP BY table_name,
         issue_type
ORDER BY table_name,
         issue_type
;

*/
